export type AutoCoin = {
  id: string;
  weex: string;
  name: string;
  fallbackMax: number;
};

/** WEEX API-tradable crypto perps (market/apiTradingSymbols). No UI-only, no TradFi stocks. */
export const TOP25: AutoCoin[] = [
  { id: "BTC", weex: "BTCUSDT", name: "Bitcoin", fallbackMax: 400 },
  { id: "ETH", weex: "ETHUSDT", name: "Ether", fallbackMax: 400 },
  { id: "BNB", weex: "BNBUSDT", name: "BNB", fallbackMax: 200 },
  { id: "XRP", weex: "XRPUSDT", name: "XRP", fallbackMax: 300 },
  { id: "SOL", weex: "SOLUSDT", name: "Solana", fallbackMax: 300 },
  { id: "DOGE", weex: "DOGEUSDT", name: "Dogecoin", fallbackMax: 200 },
  { id: "ADA", weex: "ADAUSDT", name: "Cardano", fallbackMax: 300 },
  { id: "BRETT", weex: "BRETTUSDT", name: "Brett", fallbackMax: 125 },
  { id: "LINK", weex: "LINKUSDT", name: "Chainlink", fallbackMax: 200 },
  { id: "AVAX", weex: "AVAXUSDT", name: "Avalanche", fallbackMax: 200 },
  { id: "XLM", weex: "XLMUSDT", name: "Stellar", fallbackMax: 200 },
  { id: "SUI", weex: "SUIUSDT", name: "Sui", fallbackMax: 200 },
  { id: "SHIB", weex: "1000SHIBUSDT", name: "Shiba (1000)", fallbackMax: 200 },
  { id: "BCH", weex: "BCHUSDT", name: "Bitcoin Cash", fallbackMax: 200 },
  { id: "HBAR", weex: "HBARUSDT", name: "Hedera", fallbackMax: 200 },
  { id: "LTC", weex: "LTCUSDT", name: "Litecoin", fallbackMax: 200 },
  { id: "DOT", weex: "DOTUSDT", name: "Polkadot", fallbackMax: 200 },
  { id: "UNI", weex: "UNIUSDT", name: "Uniswap", fallbackMax: 200 },
  { id: "PEPE", weex: "1000PEPEUSDT", name: "Pepe (1000)", fallbackMax: 200 },
  { id: "WIF", weex: "WIFUSDT", name: "dogwifhat", fallbackMax: 200 },
  { id: "BONK", weex: "1000BONKUSDT", name: "Bonk (1000)", fallbackMax: 200 },
  { id: "FLOKI", weex: "1000FLOKIUSDT", name: "Floki (1000)", fallbackMax: 200 },
  { id: "POPCAT", weex: "POPCATUSDT", name: "Popcat", fallbackMax: 125 },
  { id: "AAVE", weex: "AAVEUSDT", name: "Aave", fallbackMax: 200 },
  { id: "NEAR", weex: "NEARUSDT", name: "NEAR", fallbackMax: 200 },
  { id: "APT", weex: "APTUSDT", name: "Aptos", fallbackMax: 200 },
  { id: "TAO", weex: "TAOUSDT", name: "Bittensor", fallbackMax: 200 },
  { id: "INJ", weex: "INJUSDT", name: "Injective", fallbackMax: 200 },
  { id: "ARB", weex: "ARBUSDT", name: "Arbitrum", fallbackMax: 200 },
  { id: "OP", weex: "OPUSDT", name: "Optimism", fallbackMax: 200 },
  { id: "ATOM", weex: "ATOMUSDT", name: "Cosmos", fallbackMax: 200 },
  { id: "FIL", weex: "FILUSDT", name: "Filecoin", fallbackMax: 75 },
  { id: "RENDER", weex: "RENDERUSDT", name: "Render", fallbackMax: 200 },
  { id: "SEI", weex: "SEIUSDT", name: "Sei", fallbackMax: 200 },
  { id: "TIA", weex: "TIAUSDT", name: "Celestia", fallbackMax: 200 },
  { id: "FET", weex: "FETUSDT", name: "Fetch", fallbackMax: 200 },
  { id: "ICP", weex: "ICPUSDT", name: "Internet Computer", fallbackMax: 200 },
  { id: "IMX", weex: "IMXUSDT", name: "Immutable", fallbackMax: 200 },
  { id: "ETC", weex: "ETCUSDT", name: "Ethereum Classic", fallbackMax: 200 },
  { id: "JUP", weex: "JUPUSDT", name: "Jupiter", fallbackMax: 200 },
  { id: "PENDLE", weex: "PENDLEUSDT", name: "Pendle", fallbackMax: 125 },
  { id: "ONDO", weex: "ONDOUSDT", name: "Ondo", fallbackMax: 200 },
  { id: "ENA", weex: "ENAUSDT", name: "Ethena", fallbackMax: 200 },
  { id: "LDO", weex: "LDOUSDT", name: "Lido", fallbackMax: 200 },
  { id: "POL", weex: "POLUSDT", name: "Polygon", fallbackMax: 125 },
  { id: "PYTH", weex: "PYTHUSDT", name: "Pyth", fallbackMax: 200 },
  { id: "WLD", weex: "WLDUSDT", name: "Worldcoin", fallbackMax: 200 },
  { id: "ORDI", weex: "ORDIUSDT", name: "ORDI", fallbackMax: 200 },
  { id: "APE", weex: "APEUSDT", name: "ApeCoin", fallbackMax: 200 },
  { id: "PENGU", weex: "PENGUUSDT", name: "Pudgy Penguins", fallbackMax: 125 },
  { id: "RUNE", weex: "RUNEUSDT", name: "THORChain", fallbackMax: 125 },
  { id: "CRV", weex: "CRVUSDT", name: "Curve", fallbackMax: 125 },
  { id: "ENS", weex: "ENSUSDT", name: "ENS", fallbackMax: 75 },
  { id: "SAND", weex: "SANDUSDT", name: "Sandbox", fallbackMax: 200 },
  { id: "MANA", weex: "MANAUSDT", name: "Decentraland", fallbackMax: 200 },
  { id: "AXS", weex: "AXSUSDT", name: "Axie", fallbackMax: 200 },
  { id: "DYDX", weex: "DYDXUSDT", name: "dYdX", fallbackMax: 125 },
  { id: "CHZ", weex: "CHZUSDT", name: "Chiliz", fallbackMax: 200 },
  { id: "BLUR", weex: "BLURUSDT", name: "Blur", fallbackMax: 75 },
  { id: "GMX", weex: "GMXUSDT", name: "GMX", fallbackMax: 200 },
  { id: "STRK", weex: "STRKUSDT", name: "Starknet", fallbackMax: 100 },
  { id: "ZK", weex: "ZKUSDT", name: "ZKsync", fallbackMax: 75 },
  { id: "JTO", weex: "JTOUSDT", name: "Jito", fallbackMax: 200 },
  { id: "CAKE", weex: "CAKEUSDT", name: "PancakeSwap", fallbackMax: 125 },
  { id: "THETA", weex: "THETAUSDT", name: "Theta", fallbackMax: 75 },
  { id: "ALGO", weex: "ALGOUSDT", name: "Algorand", fallbackMax: 200 },
  { id: "VET", weex: "VETUSDT", name: "VeChain", fallbackMax: 125 },
  { id: "XTZ", weex: "XTZUSDT", name: "Tezos", fallbackMax: 100 },
  { id: "NEO", weex: "NEOUSDT", name: "Neo", fallbackMax: 75 },
  { id: "MINA", weex: "MINAUSDT", name: "Mina", fallbackMax: 200 },
  { id: "COMP", weex: "COMPUSDT", name: "Compound", fallbackMax: 200 },
  { id: "YFI", weex: "YFIUSDT", name: "yearn", fallbackMax: 75 },
  { id: "PEOPLE", weex: "PEOPLEUSDT", name: "People", fallbackMax: 200 },
  { id: "MOODENG", weex: "MOODENGUSDT", name: "Moodeng", fallbackMax: 200 },
  { id: "FARTCOIN", weex: "FARTCOINUSDT", name: "Fartcoin", fallbackMax: 200 },
  { id: "TRUMP", weex: "TRUMPUSDT", name: "TRUMP", fallbackMax: 200 },
  { id: "1000RATS", weex: "1000RATSUSDT", name: "Rats (1000)", fallbackMax: 125 },
  { id: "PNUT", weex: "PNUTUSDT", name: "Pnut", fallbackMax: 100 },
  { id: "SPX", weex: "SPXUSDT", name: "SPX6900", fallbackMax: 100 },
  { id: "PUMP", weex: "PUMPUSDT", name: "Pump.fun", fallbackMax: 100 },
  { id: "TURBO", weex: "TURBOUSDT", name: "Turbo", fallbackMax: 200 },
  { id: "VIRTUAL", weex: "VIRTUALUSDT", name: "Virtuals", fallbackMax: 100 },
  { id: "GRASS", weex: "GRASSUSDT", name: "Grass", fallbackMax: 200 },
  { id: "PHA", weex: "PHAUSDT", name: "Phala", fallbackMax: 125 },
  { id: "ARKM", weex: "ARKMUSDT", name: "Arkham", fallbackMax: 200 },
  { id: "XMR", weex: "XMRUSDT", name: "Monero", fallbackMax: 100 },
  { id: "ZEC", weex: "ZECUSDT", name: "Zcash", fallbackMax: 100 },
  { id: "ZEN", weex: "ZENUSDT", name: "Horizen", fallbackMax: 200 },
  { id: "XVG", weex: "XVGUSDT", name: "Verge", fallbackMax: 200 },
  { id: "DUSK", weex: "DUSKUSDT", name: "Dusk", fallbackMax: 200 },
  { id: "YGG", weex: "YGGUSDT", name: "Yield Guild", fallbackMax: 200 },
  { id: "PORTAL", weex: "PORTALUSDT", name: "Portal", fallbackMax: 75 },
  { id: "GUN", weex: "GUNUSDT", name: "Gunzilla", fallbackMax: 50 },
  { id: "ALICE", weex: "ALICEUSDT", name: "My Neighbor Alice", fallbackMax: 50 },
  { id: "AGLD", weex: "AGLDUSDT", name: "Adventure Gold", fallbackMax: 50 },
  { id: "RARE", weex: "RAREUSDT", name: "SuperRare", fallbackMax: 100 },
  { id: "KAS", weex: "KASUSDT", name: "Kaspa", fallbackMax: 200 },
  { id: "ETHFI", weex: "ETHFIUSDT", name: "ether.fi", fallbackMax: 125 },
  { id: "CVX", weex: "CVXUSDT", name: "Convex", fallbackMax: 100 },
  { id: "DRIFT", weex: "DRIFTUSDT", name: "Drift", fallbackMax: 100 },
  { id: "EIGEN", weex: "EIGENUSDT", name: "EigenLayer", fallbackMax: 100 },
  { id: "ZRO", weex: "ZROUSDT", name: "LayerZero", fallbackMax: 200 },
  { id: "JASMY", weex: "JASMYUSDT", name: "Jasmy", fallbackMax: 200 },
  { id: "QNT", weex: "QNTUSDT", name: "Quant", fallbackMax: 200 },
  { id: "CYBER", weex: "CYBERUSDT", name: "Cyber", fallbackMax: 125 },
  { id: "MANTA", weex: "MANTAUSDT", name: "Manta", fallbackMax: 50 },
  { id: "METIS", weex: "METISUSDT", name: "Metis", fallbackMax: 50 },
  { id: "AR", weex: "ARUSDT", name: "Arweave", fallbackMax: 75 },
  { id: "CELO", weex: "CELOUSDT", name: "Celo", fallbackMax: 50 },
  { id: "BERA", weex: "BERAUSDT", name: "Berachain", fallbackMax: 75 },
  { id: "LINEA", weex: "LINEAUSDT", name: "Linea", fallbackMax: 100 },
  { id: "SSV", weex: "SSVUSDT", name: "SSV", fallbackMax: 75 },
  { id: "LPT", weex: "LPTUSDT", name: "Livepeer", fallbackMax: 75 },
  { id: "BAND", weex: "BANDUSDT", name: "Band", fallbackMax: 125 },
  { id: "TRB", weex: "TRBUSDT", name: "Tellor", fallbackMax: 75 },
  { id: "AERO", weex: "AEROUSDT", name: "Aerodrome", fallbackMax: 100 },
  { id: "BB", weex: "BBUSDT", name: "BounceBit", fallbackMax: 100 },
  { id: "SONIC", weex: "SONICUSDT", name: "Sonic", fallbackMax: 50 },
  { id: "W", weex: "WUSDT", name: "Wormhole", fallbackMax: 125 },
  { id: "MORPHO", weex: "MORPHOUSDT", name: "Morpho", fallbackMax: 100 },
  { id: "DASH", weex: "DASHUSDT", name: "Dash", fallbackMax: 75 },
  { id: "C98", weex: "C98USDT", name: "Coin98", fallbackMax: 50 },
  { id: "BEL", weex: "BELUSDT", name: "Bella", fallbackMax: 75 },
  { id: "MERL", weex: "MERLUSDT", name: "Merlin", fallbackMax: 100 },
  { id: "MOVE", weex: "MOVEUSDT", name: "Movement", fallbackMax: 100 },
  { id: "KAITO", weex: "KAITOUSDT", name: "Kaito", fallbackMax: 100 },
  { id: "HMSTR", weex: "HMSTRUSDT", name: "Hamster", fallbackMax: 100 },
  { id: "PAXG", weex: "PAXGUSDT", name: "PAX Gold", fallbackMax: 50 },
  { id: "H", weex: "HUSDT", name: "Humanity", fallbackMax: 75 },
  { id: "APR", weex: "APRUSDT", name: "APR", fallbackMax: 50 },
  { id: "ASTER", weex: "ASTERUSDT", name: "ASTER", fallbackMax: 100 },
  { id: "BABY", weex: "BABYUSDT", name: "BABY", fallbackMax: 50 },
  { id: "BANK", weex: "BANKUSDT", name: "BANK", fallbackMax: 50 },
  { id: "BIRB", weex: "BIRBUSDT", name: "BIRB", fallbackMax: 50 },
  { id: "BLESS", weex: "BLESSUSDT", name: "BLESS", fallbackMax: 100 },
  { id: "BTR", weex: "BTRUSDT", name: "BTR", fallbackMax: 50 },
  { id: "BTW", weex: "BTWUSDT", name: "BTW", fallbackMax: 50 },
  { id: "COW", weex: "COWUSDT", name: "COW", fallbackMax: 50 },
  { id: "CYS", weex: "CYSUSDT", name: "CYS", fallbackMax: 50 },
  { id: "DOLO", weex: "DOLOUSDT", name: "DOLO", fallbackMax: 50 },
  { id: "DSYNC", weex: "DSYNCUSDT", name: "DSYNC", fallbackMax: 50 },
  { id: "DYM", weex: "DYMUSDT", name: "DYM", fallbackMax: 50 },
  { id: "EVAA", weex: "EVAAUSDT", name: "EVAA", fallbackMax: 50 },
  { id: "FOLKS", weex: "FOLKSUSDT", name: "FOLKS", fallbackMax: 100 },
  { id: "HEI", weex: "HEIUSDT", name: "HEI", fallbackMax: 50 },
  { id: "HOME", weex: "HOMEUSDT", name: "HOME", fallbackMax: 50 },
  { id: "IN", weex: "INUSDT", name: "IN", fallbackMax: 50 },
  { id: "IQ", weex: "IQUSDT", name: "IQ", fallbackMax: 100 },
  { id: "JELLYJELLY", weex: "JELLYJELLYUSDT", name: "JELLYJELLY", fallbackMax: 50 },
  { id: "KAT", weex: "KATUSDT", name: "KAT", fallbackMax: 50 },
  { id: "KITE", weex: "KITEUSDT", name: "KITE", fallbackMax: 50 },
  { id: "LAB", weex: "LABUSDT", name: "LAB", fallbackMax: 50 },
  { id: "LMWR", weex: "LMWRUSDT", name: "LMWR", fallbackMax: 50 },
  { id: "LYN", weex: "LYNUSDT", name: "LYN", fallbackMax: 50 },
  { id: "MEGA", weex: "MEGAUSDT", name: "MEGA", fallbackMax: 50 },
  { id: "ON", weex: "ONUSDT", name: "ON", fallbackMax: 50 },
  { id: "PARTI", weex: "PARTIUSDT", name: "PARTI", fallbackMax: 75 },
  { id: "PIEVERSE", weex: "PIEVERSEUSDT", name: "PIEVERSE", fallbackMax: 50 },
  { id: "PIPPIN", weex: "PIPPINUSDT", name: "PIPPIN", fallbackMax: 50 },
  { id: "RAVE", weex: "RAVEUSDT", name: "RAVE", fallbackMax: 50 },
  { id: "RIVER", weex: "RIVERUSDT", name: "RIVER", fallbackMax: 50 },
  { id: "SAHARA", weex: "SAHARAUSDT", name: "SAHARA", fallbackMax: 75 },
  { id: "TAC", weex: "TACUSDT", name: "TAC", fallbackMax: 50 },
  { id: "TFUEL", weex: "TFUELUSDT", name: "TFUEL", fallbackMax: 50 },
  { id: "TUT", weex: "TUTUSDT", name: "TUT", fallbackMax: 50 },
  { id: "UAI", weex: "UAIUSDT", name: "UAI", fallbackMax: 50 },
  { id: "WLFI", weex: "WLFIUSDT", name: "WLFI", fallbackMax: 100 },
  { id: "XPIN", weex: "XPINUSDT", name: "XPIN", fallbackMax: 50 },
  { id: "XPL", weex: "XPLUSDT", name: "XPL", fallbackMax: 100 },
  { id: "ZAMA", weex: "ZAMAUSDT", name: "ZAMA", fallbackMax: 50 },
  { id: "ZBT", weex: "ZBTUSDT", name: "ZBT", fallbackMax: 100 },
  { id: "ZIG", weex: "ZIGUSDT", name: "ZIG", fallbackMax: 50 },
];

export const TOP25_WEEX = TOP25.map((c) => c.weex);

/** Price-discovery / no history — never hunt, cancel working. */
export const SKIP_WEEX = new Set(["HYPEUSDT", "TONUSDT", "GRAMUSDT", "TRXUSDT", "BEAMXUSDT", "CKBUSDT", "KSMUSDT", "MNTUSDT", "ROSEUSDT", "HOTUSDT", "RIFUSDT"]);

/** Until $10k: only the tight books. */
export const CORE_WEEX = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "SOLUSDT"] as const;
export const CORE_SET = new Set<string>(CORE_WEEX);

export function coinByWeex(symbol: string): AutoCoin {
  return TOP25.find((c) => c.weex === symbol) ?? TOP25[0]!;
}
