export type AutoCoin = {
  id: string;
  weex: string;
  name: string;
  fallbackMax: number;
};

/** Known WEEX USDT-M perps only. No new listings, no TON/HYPE/TRX. */
export const TOP25: AutoCoin[] = [
  { id: "BTC", weex: "BTCUSDT", name: "Bitcoin", fallbackMax: 400 },
  { id: "ETH", weex: "ETHUSDT", name: "Ether", fallbackMax: 400 },
  { id: "BNB", weex: "BNBUSDT", name: "BNB", fallbackMax: 200 },
  { id: "XRP", weex: "XRPUSDT", name: "XRP", fallbackMax: 300 },
  { id: "SOL", weex: "SOLUSDT", name: "Solana", fallbackMax: 300 },
  { id: "DOGE", weex: "DOGEUSDT", name: "Dogecoin", fallbackMax: 200 },
  { id: "ADA", weex: "ADAUSDT", name: "Cardano", fallbackMax: 300 },
  { id: "BRETT", weex: "BRETTUSDT", name: "Brett", fallbackMax: 125 },
  { id: "LINK", weex: "LINKUSDT", name: "Chainlink", fallbackMax: 200 },
  { id: "AVAX", weex: "AVAXUSDT", name: "Avalanche", fallbackMax: 200 },
  { id: "XLM", weex: "XLMUSDT", name: "Stellar", fallbackMax: 200 },
  { id: "SUI", weex: "SUIUSDT", name: "Sui", fallbackMax: 200 },
  { id: "SHIB", weex: "1000SHIBUSDT", name: "Shiba (1000)", fallbackMax: 200 },
  { id: "BCH", weex: "BCHUSDT", name: "Bitcoin Cash", fallbackMax: 200 },
  { id: "HBAR", weex: "HBARUSDT", name: "Hedera", fallbackMax: 200 },
  { id: "LTC", weex: "LTCUSDT", name: "Litecoin", fallbackMax: 200 },
  { id: "DOT", weex: "DOTUSDT", name: "Polkadot", fallbackMax: 200 },
  { id: "UNI", weex: "UNIUSDT", name: "Uniswap", fallbackMax: 200 },
  { id: "PEPE", weex: "1000PEPEUSDT", name: "Pepe (1000)", fallbackMax: 200 },
  { id: "WIF", weex: "WIFUSDT", name: "dogwifhat", fallbackMax: 200 },
  { id: "BONK", weex: "1000BONKUSDT", name: "Bonk (1000)", fallbackMax: 200 },
  { id: "FLOKI", weex: "1000FLOKIUSDT", name: "Floki (1000)", fallbackMax: 200 },
  { id: "MEME", weex: "MEMEUSDT", name: "Memecoin", fallbackMax: 125 },
  { id: "POPCAT", weex: "POPCATUSDT", name: "Popcat", fallbackMax: 125 },
  { id: "AAVE", weex: "AAVEUSDT", name: "Aave", fallbackMax: 200 },
  { id: "NEAR", weex: "NEARUSDT", name: "NEAR", fallbackMax: 200 },
  { id: "APT", weex: "APTUSDT", name: "Aptos", fallbackMax: 200 },
  { id: "TAO", weex: "TAOUSDT", name: "Bittensor", fallbackMax: 200 },
  { id: "INJ", weex: "INJUSDT", name: "Injective", fallbackMax: 200 },
  { id: "ARB", weex: "ARBUSDT", name: "Arbitrum", fallbackMax: 200 },
  { id: "OP", weex: "OPUSDT", name: "Optimism", fallbackMax: 200 },
  { id: "ATOM", weex: "ATOMUSDT", name: "Cosmos", fallbackMax: 200 },
  { id: "FIL", weex: "FILUSDT", name: "Filecoin", fallbackMax: 75 },
  { id: "RENDER", weex: "RENDERUSDT", name: "Render", fallbackMax: 200 },
  { id: "SEI", weex: "SEIUSDT", name: "Sei", fallbackMax: 200 },
  { id: "TIA", weex: "TIAUSDT", name: "Celestia", fallbackMax: 200 },
  { id: "FET", weex: "FETUSDT", name: "Fetch", fallbackMax: 200 },
  { id: "ICP", weex: "ICPUSDT", name: "Internet Computer", fallbackMax: 200 },
  { id: "IMX", weex: "IMXUSDT", name: "Immutable", fallbackMax: 200 },
  { id: "ETC", weex: "ETCUSDT", name: "Ethereum Classic", fallbackMax: 200 },
  { id: "JUP", weex: "JUPUSDT", name: "Jupiter", fallbackMax: 200 },
  { id: "PENDLE", weex: "PENDLEUSDT", name: "Pendle", fallbackMax: 125 },
  { id: "ONDO", weex: "ONDOUSDT", name: "Ondo", fallbackMax: 200 },
  { id: "ENA", weex: "ENAUSDT", name: "Ethena", fallbackMax: 200 },
  { id: "LDO", weex: "LDOUSDT", name: "Lido", fallbackMax: 200 },
  { id: "POL", weex: "POLUSDT", name: "Polygon", fallbackMax: 125 },
  { id: "PYTH", weex: "PYTHUSDT", name: "Pyth", fallbackMax: 200 },
  { id: "WLD", weex: "WLDUSDT", name: "Worldcoin", fallbackMax: 200 },
  { id: "GRT", weex: "GRTUSDT", name: "The Graph", fallbackMax: 200 },
  { id: "ORDI", weex: "ORDIUSDT", name: "ORDI", fallbackMax: 200 },
  { id: "APE", weex: "APEUSDT", name: "ApeCoin", fallbackMax: 200 },
  { id: "PENGU", weex: "PENGUUSDT", name: "Pudgy Penguins", fallbackMax: 125 },
  { id: "RUNE", weex: "RUNEUSDT", name: "THORChain", fallbackMax: 125 },
  { id: "CRV", weex: "CRVUSDT", name: "Curve", fallbackMax: 125 },
  { id: "ENS", weex: "ENSUSDT", name: "ENS", fallbackMax: 75 },
  { id: "GALA", weex: "GALAUSDT", name: "Gala", fallbackMax: 125 },
  { id: "SAND", weex: "SANDUSDT", name: "Sandbox", fallbackMax: 200 },
  { id: "MANA", weex: "MANAUSDT", name: "Decentraland", fallbackMax: 200 },
  { id: "AXS", weex: "AXSUSDT", name: "Axie", fallbackMax: 200 },
  { id: "DYDX", weex: "DYDXUSDT", name: "dYdX", fallbackMax: 125 },
  { id: "SNX", weex: "SNXUSDT", name: "Synthetix", fallbackMax: 100 },
  { id: "CHZ", weex: "CHZUSDT", name: "Chiliz", fallbackMax: 200 },
  { id: "BLUR", weex: "BLURUSDT", name: "Blur", fallbackMax: 75 },
  { id: "GMX", weex: "GMXUSDT", name: "GMX", fallbackMax: 200 },
  { id: "STRK", weex: "STRKUSDT", name: "Starknet", fallbackMax: 100 },
  { id: "ZK", weex: "ZKUSDT", name: "ZKsync", fallbackMax: 75 },
  { id: "JTO", weex: "JTOUSDT", name: "Jito", fallbackMax: 200 },
  { id: "CAKE", weex: "CAKEUSDT", name: "PancakeSwap", fallbackMax: 125 },
  { id: "THETA", weex: "THETAUSDT", name: "Theta", fallbackMax: 75 },
  { id: "EGLD", weex: "EGLDUSDT", name: "MultiversX", fallbackMax: 125 },
  { id: "ALGO", weex: "ALGOUSDT", name: "Algorand", fallbackMax: 200 },
  { id: "VET", weex: "VETUSDT", name: "VeChain", fallbackMax: 125 },
  { id: "XTZ", weex: "XTZUSDT", name: "Tezos", fallbackMax: 100 },
  { id: "NEO", weex: "NEOUSDT", name: "Neo", fallbackMax: 75 },
  { id: "IOTA", weex: "IOTAUSDT", name: "IOTA", fallbackMax: 125 },
  { id: "KAVA", weex: "KAVAUSDT", name: "Kava", fallbackMax: 200 },
  { id: "FLOW", weex: "FLOWUSDT", name: "Flow", fallbackMax: 200 },
  { id: "MINA", weex: "MINAUSDT", name: "Mina", fallbackMax: 200 },
  { id: "1INCH", weex: "1INCHUSDT", name: "1inch", fallbackMax: 200 },
  { id: "COMP", weex: "COMPUSDT", name: "Compound", fallbackMax: 200 },
  { id: "YFI", weex: "YFIUSDT", name: "yearn", fallbackMax: 75 },
  { id: "CRO", weex: "CROUSDT", name: "Cronos", fallbackMax: 200 },
  { id: "PEOPLE", weex: "PEOPLEUSDT", name: "People", fallbackMax: 200 },
  { id: "BOME", weex: "BOMEUSDT", name: "Book of Meme", fallbackMax: 200 },
  { id: "MEW", weex: "MEWUSDT", name: "MEW", fallbackMax: 200 },
  { id: "MOODENG", weex: "MOODENGUSDT", name: "Moodeng", fallbackMax: 200 },
  { id: "FARTCOIN", weex: "FARTCOINUSDT", name: "Fartcoin", fallbackMax: 200 },
  { id: "NEIROCTO", weex: "NEIROCTOUSDT", name: "Neiro", fallbackMax: 200 },
  { id: "TRUMP", weex: "TRUMPUSDT", name: "TRUMP", fallbackMax: 200 },
  { id: "1000RATS", weex: "1000RATSUSDT", name: "Rats (1000)", fallbackMax: 125 },
  { id: "PNUT", weex: "PNUTUSDT", name: "Pnut", fallbackMax: 100 },
  { id: "CHILLGUY", weex: "CHILLGUYUSDT", name: "Chill Guy", fallbackMax: 100 },
  { id: "SPX", weex: "SPXUSDT", name: "SPX6900", fallbackMax: 100 },
  { id: "KOMA", weex: "KOMAUSDT", name: "Koma Inu", fallbackMax: 100 },
  { id: "BAN", weex: "BANUSDT", name: "Comedian", fallbackMax: 100 },
  { id: "PUMP", weex: "PUMPUSDT", name: "Pump.fun", fallbackMax: 100 },
  { id: "TURBO", weex: "TURBOUSDT", name: "Turbo", fallbackMax: 200 },
  { id: "GOAT", weex: "GOATUSDT", name: "Goatseus", fallbackMax: 200 },
  { id: "CAT", weex: "CATUSDT", name: "Simon's Cat", fallbackMax: 100 },
  { id: "1000SATS", weex: "1000SATSUSDT", name: "SATS (1000)", fallbackMax: 100 },
  { id: "VIRTUAL", weex: "VIRTUALUSDT", name: "Virtuals", fallbackMax: 100 },
  { id: "AIXBT", weex: "AIXBTUSDT", name: "aixbt", fallbackMax: 100 },
  { id: "CGPT", weex: "CGPTUSDT", name: "ChainGPT", fallbackMax: 100 },
  { id: "GRASS", weex: "GRASSUSDT", name: "Grass", fallbackMax: 200 },
  { id: "IO", weex: "IOUSDT", name: "io.net", fallbackMax: 125 },
  { id: "RLC", weex: "RLCUSDT", name: "iExec", fallbackMax: 125 },
  { id: "NMR", weex: "NMRUSDT", name: "Numeraire", fallbackMax: 100 },
  { id: "AKT", weex: "AKTUSDT", name: "Akash", fallbackMax: 100 },
  { id: "ARC", weex: "ARCUSDT", name: "AI Rig Complex", fallbackMax: 100 },
  { id: "COOKIE", weex: "COOKIEUSDT", name: "Cookie DAO", fallbackMax: 100 },
  { id: "PHA", weex: "PHAUSDT", name: "Phala", fallbackMax: 125 },
  { id: "FLUX", weex: "FLUXUSDT", name: "Flux", fallbackMax: 100 },
  { id: "FLOCK", weex: "FLOCKUSDT", name: "Flock", fallbackMax: 100 },
  { id: "ARKM", weex: "ARKMUSDT", name: "Arkham", fallbackMax: 200 },
  { id: "GLM", weex: "GLMUSDT", name: "Golem", fallbackMax: 125 },
  { id: "CHR", weex: "CHRUSDT", name: "Chromia", fallbackMax: 100 },
  { id: "XMR", weex: "XMRUSDT", name: "Monero", fallbackMax: 100 },
  { id: "ZEC", weex: "ZECUSDT", name: "Zcash", fallbackMax: 100 },
  { id: "ZEN", weex: "ZENUSDT", name: "Horizen", fallbackMax: 200 },
  { id: "XVG", weex: "XVGUSDT", name: "Verge", fallbackMax: 200 },
  { id: "ROSE", weex: "ROSEUSDT", name: "Oasis", fallbackMax: 100 },
  { id: "DUSK", weex: "DUSKUSDT", name: "Dusk", fallbackMax: 200 },
  { id: "SCR", weex: "SCRUSDT", name: "Scroll", fallbackMax: 125 },
  { id: "NAORIS", weex: "NAORISUSDT", name: "Naoris", fallbackMax: 100 },
  { id: "YGG", weex: "YGGUSDT", name: "Yield Guild", fallbackMax: 200 },
  { id: "BIGTIME", weex: "BIGTIMEUSDT", name: "Big Time", fallbackMax: 125 },
  { id: "SLP", weex: "SLPUSDT", name: "Smooth Love Potion", fallbackMax: 125 },
  { id: "ENJ", weex: "ENJUSDT", name: "Enjin", fallbackMax: 75 },
  { id: "PIXEL", weex: "PIXELUSDT", name: "Pixels", fallbackMax: 50 },
  { id: "BEAMX", weex: "BEAMXUSDT", name: "Beam", fallbackMax: 75 },
  { id: "PORTAL", weex: "PORTALUSDT", name: "Portal", fallbackMax: 75 },
  { id: "XAI", weex: "XAIUSDT", name: "Xai", fallbackMax: 75 },
  { id: "RONIN", weex: "RONINUSDT", name: "Ronin", fallbackMax: 50 },
  { id: "SUPER", weex: "SUPERUSDT", name: "SuperVerse", fallbackMax: 75 },
  { id: "GUN", weex: "GUNUSDT", name: "Gunzilla", fallbackMax: 50 },
  { id: "MAGIC", weex: "MAGICUSDT", name: "Treasure", fallbackMax: 200 },
  { id: "ILV", weex: "ILVUSDT", name: "Illuvium", fallbackMax: 75 },
  { id: "ALICE", weex: "ALICEUSDT", name: "My Neighbor Alice", fallbackMax: 50 },
  { id: "GMT", weex: "GMTUSDT", name: "STEPN", fallbackMax: 50 },
  { id: "TLM", weex: "TLMUSDT", name: "Alien Worlds", fallbackMax: 125 },
  { id: "MAVIA", weex: "MAVIAUSDT", name: "Heroes of Mavia", fallbackMax: 100 },
  { id: "AGLD", weex: "AGLDUSDT", name: "Adventure Gold", fallbackMax: 50 },
  { id: "WAXP", weex: "WAXPUSDT", name: "WAX", fallbackMax: 50 },
  { id: "NXPC", weex: "NXPCUSDT", name: "MapleStory Nexpace", fallbackMax: 100 },
  { id: "ME", weex: "MEUSDT", name: "Magic Eden", fallbackMax: 100 },
  { id: "RARE", weex: "RAREUSDT", name: "SuperRare", fallbackMax: 100 },
  { id: "ANIME", weex: "ANIMEUSDT", name: "Anime", fallbackMax: 50 },
  { id: "MOCA", weex: "MOCAUSDT", name: "Moca", fallbackMax: 50 },
  { id: "KAS", weex: "KASUSDT", name: "Kaspa", fallbackMax: 200 },
  { id: "ETHFI", weex: "ETHFIUSDT", name: "ether.fi", fallbackMax: 125 },
  { id: "RAY", weex: "RAYUSDT", name: "Raydium", fallbackMax: 100 },
  { id: "CVX", weex: "CVXUSDT", name: "Convex", fallbackMax: 100 },
  { id: "WOO", weex: "WOOUSDT", name: "WOO", fallbackMax: 200 },
  { id: "KNC", weex: "KNCUSDT", name: "Kyber", fallbackMax: 200 },
  { id: "CETUS", weex: "CETUSUSDT", name: "Cetus", fallbackMax: 200 },
  { id: "DRIFT", weex: "DRIFTUSDT", name: "Drift", fallbackMax: 100 },
  { id: "EIGEN", weex: "EIGENUSDT", name: "EigenLayer", fallbackMax: 100 },
  { id: "ZRO", weex: "ZROUSDT", name: "LayerZero", fallbackMax: 200 },
  { id: "JASMY", weex: "JASMYUSDT", name: "Jasmy", fallbackMax: 200 },
  { id: "MASK", weex: "MASKUSDT", name: "Mask", fallbackMax: 200 },
  { id: "QNT", weex: "QNTUSDT", name: "Quant", fallbackMax: 200 },
  { id: "CYBER", weex: "CYBERUSDT", name: "Cyber", fallbackMax: 125 },
  { id: "BAT", weex: "BATUSDT", name: "Basic Attention", fallbackMax: 125 },
  { id: "API3", weex: "API3USDT", name: "API3", fallbackMax: 100 },
  { id: "HNT", weex: "HNTUSDT", name: "Helium", fallbackMax: 100 },
  { id: "SKL", weex: "SKLUSDT", name: "Skale", fallbackMax: 125 },
  { id: "CELR", weex: "CELRUSDT", name: "Celer", fallbackMax: 125 },
  { id: "MANTA", weex: "MANTAUSDT", name: "Manta", fallbackMax: 50 },
  { id: "METIS", weex: "METISUSDT", name: "Metis", fallbackMax: 50 },
  { id: "CFX", weex: "CFXUSDT", name: "Conflux", fallbackMax: 125 },
  { id: "CKB", weex: "CKBUSDT", name: "Nervos", fallbackMax: 125 },
  { id: "RVN", weex: "RVNUSDT", name: "Ravencoin", fallbackMax: 125 },
  { id: "ONT", weex: "ONTUSDT", name: "Ontology", fallbackMax: 125 },
  { id: "AR", weex: "ARUSDT", name: "Arweave", fallbackMax: 75 },
  { id: "QTUM", weex: "QTUMUSDT", name: "Qtum", fallbackMax: 75 },
  { id: "CELO", weex: "CELOUSDT", name: "Celo", fallbackMax: 50 },
  { id: "KSM", weex: "KSMUSDT", name: "Kusama", fallbackMax: 50 },
  { id: "ZETA", weex: "ZETAUSDT", name: "ZetaChain", fallbackMax: 75 },
  { id: "BERA", weex: "BERAUSDT", name: "Berachain", fallbackMax: 75 },
  { id: "PLUME", weex: "PLUMEUSDT", name: "Plume", fallbackMax: 75 },
  { id: "LINEA", weex: "LINEAUSDT", name: "Linea", fallbackMax: 100 },
];

export const TOP25_WEEX = TOP25.map((c) => c.weex);

/** Price-discovery / no history — never hunt, cancel working. */
export const SKIP_WEEX = new Set(["HYPEUSDT", "TONUSDT", "GRAMUSDT", "TRXUSDT"]);

/** Until $10k: only the tight books. */
export const CORE_WEEX = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "SOLUSDT"] as const;
export const CORE_SET = new Set<string>(CORE_WEEX);

export function coinByWeex(symbol: string): AutoCoin {
  return TOP25.find((c) => c.weex === symbol) ?? TOP25[0]!;
}
