export type AutoCoin = {
  id: string;
  weex: string;
  name: string;
  fallbackMax: number;
};

/** Known WEEX USDT-M perps only. No new listings, no TON/HYPE/TRX. */
export const TOP25: AutoCoin[] = [
  { id: "BTC", weex: "BTCUSDT", name: "Bitcoin", fallbackMax: 400 },
  { id: "ETH", weex: "ETHUSDT", name: "Ether", fallbackMax: 400 },
  { id: "BNB", weex: "BNBUSDT", name: "BNB", fallbackMax: 200 },
  { id: "XRP", weex: "XRPUSDT", name: "XRP", fallbackMax: 300 },
  { id: "SOL", weex: "SOLUSDT", name: "Solana", fallbackMax: 300 },
  { id: "DOGE", weex: "DOGEUSDT", name: "Dogecoin", fallbackMax: 200 },
  { id: "ADA", weex: "ADAUSDT", name: "Cardano", fallbackMax: 300 },
  { id: "BRETT", weex: "BRETTUSDT", name: "Brett", fallbackMax: 125 },
  { id: "LINK", weex: "LINKUSDT", name: "Chainlink", fallbackMax: 200 },
  { id: "AVAX", weex: "AVAXUSDT", name: "Avalanche", fallbackMax: 200 },
  { id: "XLM", weex: "XLMUSDT", name: "Stellar", fallbackMax: 200 },
  { id: "SUI", weex: "SUIUSDT", name: "Sui", fallbackMax: 200 },
  { id: "SHIB", weex: "1000SHIBUSDT", name: "Shiba (1000)", fallbackMax: 200 },
  { id: "BCH", weex: "BCHUSDT", name: "Bitcoin Cash", fallbackMax: 200 },
  { id: "HBAR", weex: "HBARUSDT", name: "Hedera", fallbackMax: 200 },
  { id: "LTC", weex: "LTCUSDT", name: "Litecoin", fallbackMax: 200 },
  { id: "DOT", weex: "DOTUSDT", name: "Polkadot", fallbackMax: 200 },
  { id: "UNI", weex: "UNIUSDT", name: "Uniswap", fallbackMax: 200 },
  { id: "PEPE", weex: "1000PEPEUSDT", name: "Pepe (1000)", fallbackMax: 200 },
  { id: "WIF", weex: "WIFUSDT", name: "dogwifhat", fallbackMax: 200 },
  { id: "BONK", weex: "1000BONKUSDT", name: "Bonk (1000)", fallbackMax: 200 },
  { id: "FLOKI", weex: "1000FLOKIUSDT", name: "Floki (1000)", fallbackMax: 200 },
  { id: "MEME", weex: "MEMEUSDT", name: "Memecoin", fallbackMax: 125 },
  { id: "POPCAT", weex: "POPCATUSDT", name: "Popcat", fallbackMax: 125 },
  { id: "AAVE", weex: "AAVEUSDT", name: "Aave", fallbackMax: 200 },
  { id: "NEAR", weex: "NEARUSDT", name: "NEAR", fallbackMax: 200 },
  { id: "APT", weex: "APTUSDT", name: "Aptos", fallbackMax: 200 },
  { id: "TAO", weex: "TAOUSDT", name: "Bittensor", fallbackMax: 200 },
  { id: "INJ", weex: "INJUSDT", name: "Injective", fallbackMax: 200 },
  { id: "ARB", weex: "ARBUSDT", name: "Arbitrum", fallbackMax: 200 },
  { id: "OP", weex: "OPUSDT", name: "Optimism", fallbackMax: 200 },
  { id: "ATOM", weex: "ATOMUSDT", name: "Cosmos", fallbackMax: 200 },
  { id: "FIL", weex: "FILUSDT", name: "Filecoin", fallbackMax: 75 },
  { id: "RENDER", weex: "RENDERUSDT", name: "Render", fallbackMax: 200 },
  { id: "SEI", weex: "SEIUSDT", name: "Sei", fallbackMax: 200 },
  { id: "TIA", weex: "TIAUSDT", name: "Celestia", fallbackMax: 200 },
  { id: "FET", weex: "FETUSDT", name: "Fetch", fallbackMax: 200 },
  { id: "ICP", weex: "ICPUSDT", name: "Internet Computer", fallbackMax: 200 },
  { id: "IMX", weex: "IMXUSDT", name: "Immutable", fallbackMax: 200 },
  { id: "ETC", weex: "ETCUSDT", name: "Ethereum Classic", fallbackMax: 200 },
  { id: "JUP", weex: "JUPUSDT", name: "Jupiter", fallbackMax: 200 },
  { id: "PENDLE", weex: "PENDLEUSDT", name: "Pendle", fallbackMax: 125 },
  { id: "ONDO", weex: "ONDOUSDT", name: "Ondo", fallbackMax: 200 },
  { id: "ENA", weex: "ENAUSDT", name: "Ethena", fallbackMax: 200 },
  { id: "LDO", weex: "LDOUSDT", name: "Lido", fallbackMax: 200 },
  { id: "POL", weex: "POLUSDT", name: "Polygon", fallbackMax: 125 },
  { id: "PYTH", weex: "PYTHUSDT", name: "Pyth", fallbackMax: 200 },
  { id: "WLD", weex: "WLDUSDT", name: "Worldcoin", fallbackMax: 200 },
  { id: "GRT", weex: "GRTUSDT", name: "The Graph", fallbackMax: 200 },
  { id: "ORDI", weex: "ORDIUSDT", name: "ORDI", fallbackMax: 200 },
  { id: "APE", weex: "APEUSDT", name: "ApeCoin", fallbackMax: 200 },
  { id: "PENGU", weex: "PENGUUSDT", name: "Pudgy Penguins", fallbackMax: 125 },
  { id: "RUNE", weex: "RUNEUSDT", name: "THORChain", fallbackMax: 125 },
  { id: "CRV", weex: "CRVUSDT", name: "Curve", fallbackMax: 125 },
  { id: "ENS", weex: "ENSUSDT", name: "ENS", fallbackMax: 75 },
  { id: "GALA", weex: "GALAUSDT", name: "Gala", fallbackMax: 125 },
  { id: "SAND", weex: "SANDUSDT", name: "Sandbox", fallbackMax: 200 },
  { id: "MANA", weex: "MANAUSDT", name: "Decentraland", fallbackMax: 200 },
  { id: "AXS", weex: "AXSUSDT", name: "Axie", fallbackMax: 200 },
  { id: "DYDX", weex: "DYDXUSDT", name: "dYdX", fallbackMax: 125 },
  { id: "SNX", weex: "SNXUSDT", name: "Synthetix", fallbackMax: 100 },
  { id: "CHZ", weex: "CHZUSDT", name: "Chiliz", fallbackMax: 200 },
  { id: "BLUR", weex: "BLURUSDT", name: "Blur", fallbackMax: 75 },
  { id: "GMX", weex: "GMXUSDT", name: "GMX", fallbackMax: 200 },
  { id: "STRK", weex: "STRKUSDT", name: "Starknet", fallbackMax: 100 },
  { id: "ZK", weex: "ZKUSDT", name: "ZKsync", fallbackMax: 75 },
  { id: "JTO", weex: "JTOUSDT", name: "Jito", fallbackMax: 200 },
  { id: "CAKE", weex: "CAKEUSDT", name: "PancakeSwap", fallbackMax: 125 },
  { id: "THETA", weex: "THETAUSDT", name: "Theta", fallbackMax: 75 },
  { id: "EGLD", weex: "EGLDUSDT", name: "MultiversX", fallbackMax: 125 },
  { id: "ALGO", weex: "ALGOUSDT", name: "Algorand", fallbackMax: 200 },
  { id: "VET", weex: "VETUSDT", name: "VeChain", fallbackMax: 125 },
  { id: "XTZ", weex: "XTZUSDT", name: "Tezos", fallbackMax: 100 },
  { id: "NEO", weex: "NEOUSDT", name: "Neo", fallbackMax: 75 },
  { id: "IOTA", weex: "IOTAUSDT", name: "IOTA", fallbackMax: 125 },
  { id: "KAVA", weex: "KAVAUSDT", name: "Kava", fallbackMax: 200 },
  { id: "FLOW", weex: "FLOWUSDT", name: "Flow", fallbackMax: 200 },
  { id: "MINA", weex: "MINAUSDT", name: "Mina", fallbackMax: 200 },
  { id: "1INCH", weex: "1INCHUSDT", name: "1inch", fallbackMax: 200 },
  { id: "COMP", weex: "COMPUSDT", name: "Compound", fallbackMax: 200 },
  { id: "YFI", weex: "YFIUSDT", name: "yearn", fallbackMax: 75 },
  { id: "CRO", weex: "CROUSDT", name: "Cronos", fallbackMax: 200 },
  { id: "PEOPLE", weex: "PEOPLEUSDT", name: "People", fallbackMax: 200 },
  { id: "BOME", weex: "BOMEUSDT", name: "Book of Meme", fallbackMax: 200 },
  { id: "MEW", weex: "MEWUSDT", name: "MEW", fallbackMax: 200 },
  { id: "MOODENG", weex: "MOODENGUSDT", name: "Moodeng", fallbackMax: 200 },
  { id: "FARTCOIN", weex: "FARTCOINUSDT", name: "Fartcoin", fallbackMax: 200 },
  { id: "NEIROCTO", weex: "NEIROCTOUSDT", name: "Neiro", fallbackMax: 200 },
  { id: "TRUMP", weex: "TRUMPUSDT", name: "TRUMP", fallbackMax: 200 },
  { id: "1000RATS", weex: "1000RATSUSDT", name: "Rats (1000)", fallbackMax: 125 },
  { id: "PNUT", weex: "PNUTUSDT", name: "Pnut", fallbackMax: 100 },
  { id: "CHILLGUY", weex: "CHILLGUYUSDT", name: "Chill Guy", fallbackMax: 100 },
  { id: "SPX", weex: "SPXUSDT", name: "SPX6900", fallbackMax: 100 },
  { id: "KOMA", weex: "KOMAUSDT", name: "Koma Inu", fallbackMax: 100 },
  { id: "BAN", weex: "BANUSDT", name: "Comedian", fallbackMax: 100 },
  { id: "PUMP", weex: "PUMPUSDT", name: "Pump.fun", fallbackMax: 100 },
  { id: "TURBO", weex: "TURBOUSDT", name: "Turbo", fallbackMax: 200 },
  { id: "GOAT", weex: "GOATUSDT", name: "Goatseus", fallbackMax: 200 },
  { id: "CAT", weex: "CATUSDT", name: "Simon's Cat", fallbackMax: 100 },
  { id: "1000SATS", weex: "1000SATSUSDT", name: "SATS (1000)", fallbackMax: 100 },
  { id: "VIRTUAL", weex: "VIRTUALUSDT", name: "Virtuals", fallbackMax: 100 },
  { id: "AIXBT", weex: "AIXBTUSDT", name: "aixbt", fallbackMax: 100 },
  { id: "CGPT", weex: "CGPTUSDT", name: "ChainGPT", fallbackMax: 100 },
  { id: "GRASS", weex: "GRASSUSDT", name: "Grass", fallbackMax: 200 },
  { id: "IO", weex: "IOUSDT", name: "io.net", fallbackMax: 125 },
  { id: "RLC", weex: "RLCUSDT", name: "iExec", fallbackMax: 125 },
  { id: "NMR", weex: "NMRUSDT", name: "Numeraire", fallbackMax: 100 },
  { id: "AKT", weex: "AKTUSDT", name: "Akash", fallbackMax: 100 },
  { id: "ARC", weex: "ARCUSDT", name: "AI Rig Complex", fallbackMax: 100 },
  { id: "COOKIE", weex: "COOKIEUSDT", name: "Cookie DAO", fallbackMax: 100 },
  { id: "PHA", weex: "PHAUSDT", name: "Phala", fallbackMax: 125 },
  { id: "FLUX", weex: "FLUXUSDT", name: "Flux", fallbackMax: 100 },
  { id: "FLOCK", weex: "FLOCKUSDT", name: "Flock", fallbackMax: 100 },
  { id: "ARKM", weex: "ARKMUSDT", name: "Arkham", fallbackMax: 200 },
  { id: "GLM", weex: "GLMUSDT", name: "Golem", fallbackMax: 125 },
  { id: "CHR", weex: "CHRUSDT", name: "Chromia", fallbackMax: 100 },
  { id: "XMR", weex: "XMRUSDT", name: "Monero", fallbackMax: 100 },
  { id: "ZEC", weex: "ZECUSDT", name: "Zcash", fallbackMax: 100 },
  { id: "ZEN", weex: "ZENUSDT", name: "Horizen", fallbackMax: 200 },
  { id: "XVG", weex: "XVGUSDT", name: "Verge", fallbackMax: 200 },
  { id: "ROSE", weex: "ROSEUSDT", name: "Oasis", fallbackMax: 100 },
  { id: "DUSK", weex: "DUSKUSDT", name: "Dusk", fallbackMax: 200 },
  { id: "SCR", weex: "SCRUSDT", name: "Scroll", fallbackMax: 125 },
  { id: "NAORIS", weex: "NAORISUSDT", name: "Naoris", fallbackMax: 100 },
  { id: "YGG", weex: "YGGUSDT", name: "Yield Guild", fallbackMax: 200 },
  { id: "BIGTIME", weex: "BIGTIMEUSDT", name: "Big Time", fallbackMax: 125 },
  { id: "SLP", weex: "SLPUSDT", name: "Smooth Love Potion", fallbackMax: 125 },
  { id: "ENJ", weex: "ENJUSDT", name: "Enjin", fallbackMax: 75 },
  { id: "PIXEL", weex: "PIXELUSDT", name: "Pixels", fallbackMax: 50 },
  { id: "BEAMX", weex: "BEAMXUSDT", name: "Beam", fallbackMax: 75 },
  { id: "PORTAL", weex: "PORTALUSDT", name: "Portal", fallbackMax: 75 },
  { id: "XAI", weex: "XAIUSDT", name: "Xai", fallbackMax: 75 },
  { id: "RONIN", weex: "RONINUSDT", name: "Ronin", fallbackMax: 50 },
  { id: "SUPER", weex: "SUPERUSDT", name: "SuperVerse", fallbackMax: 75 },
  { id: "GUN", weex: "GUNUSDT", name: "Gunzilla", fallbackMax: 50 },
  { id: "MAGIC", weex: "MAGICUSDT", name: "Treasure", fallbackMax: 200 },
  { id: "ILV", weex: "ILVUSDT", name: "Illuvium", fallbackMax: 75 },
  { id: "ALICE", weex: "ALICEUSDT", name: "My Neighbor Alice", fallbackMax: 50 },
  { id: "GMT", weex: "GMTUSDT", name: "STEPN", fallbackMax: 50 },
  { id: "TLM", weex: "TLMUSDT", name: "Alien Worlds", fallbackMax: 125 },
  { id: "MAVIA", weex: "MAVIAUSDT", name: "Heroes of Mavia", fallbackMax: 100 },
  { id: "AGLD", weex: "AGLDUSDT", name: "Adventure Gold", fallbackMax: 50 },
  { id: "WAXP", weex: "WAXPUSDT", name: "WAX", fallbackMax: 50 },
  { id: "NXPC", weex: "NXPCUSDT", name: "MapleStory Nexpace", fallbackMax: 100 },
  { id: "ME", weex: "MEUSDT", name: "Magic Eden", fallbackMax: 100 },
  { id: "RARE", weex: "RAREUSDT", name: "SuperRare", fallbackMax: 100 },
  { id: "ANIME", weex: "ANIMEUSDT", name: "Anime", fallbackMax: 50 },
  { id: "MOCA", weex: "MOCAUSDT", name: "Moca", fallbackMax: 50 },
  { id: "KAS", weex: "KASUSDT", name: "Kaspa", fallbackMax: 200 },
  { id: "ETHFI", weex: "ETHFIUSDT", name: "ether.fi", fallbackMax: 125 },
  { id: "RAY", weex: "RAYUSDT", name: "Raydium", fallbackMax: 100 },
  { id: "CVX", weex: "CVXUSDT", name: "Convex", fallbackMax: 100 },
  { id: "WOO", weex: "WOOUSDT", name: "WOO", fallbackMax: 200 },
  { id: "KNC", weex: "KNCUSDT", name: "Kyber", fallbackMax: 200 },
  { id: "CETUS", weex: "CETUSUSDT", name: "Cetus", fallbackMax: 200 },
  { id: "DRIFT", weex: "DRIFTUSDT", name: "Drift", fallbackMax: 100 },
  { id: "EIGEN", weex: "EIGENUSDT", name: "EigenLayer", fallbackMax: 100 },
  { id: "ZRO", weex: "ZROUSDT", name: "LayerZero", fallbackMax: 200 },
  { id: "JASMY", weex: "JASMYUSDT", name: "Jasmy", fallbackMax: 200 },
  { id: "MASK", weex: "MASKUSDT", name: "Mask", fallbackMax: 200 },
  { id: "QNT", weex: "QNTUSDT", name: "Quant", fallbackMax: 200 },
  { id: "CYBER", weex: "CYBERUSDT", name: "Cyber", fallbackMax: 125 },
  { id: "BAT", weex: "BATUSDT", name: "Basic Attention", fallbackMax: 125 },
  { id: "API3", weex: "API3USDT", name: "API3", fallbackMax: 100 },
  { id: "HNT", weex: "HNTUSDT", name: "Helium", fallbackMax: 100 },
  { id: "SKL", weex: "SKLUSDT", name: "Skale", fallbackMax: 125 },
  { id: "CELR", weex: "CELRUSDT", name: "Celer", fallbackMax: 125 },
  { id: "MANTA", weex: "MANTAUSDT", name: "Manta", fallbackMax: 50 },
  { id: "METIS", weex: "METISUSDT", name: "Metis", fallbackMax: 50 },
  { id: "CFX", weex: "CFXUSDT", name: "Conflux", fallbackMax: 125 },
  { id: "CKB", weex: "CKBUSDT", name: "Nervos", fallbackMax: 125 },
  { id: "RVN", weex: "RVNUSDT", name: "Ravencoin", fallbackMax: 125 },
  { id: "ONT", weex: "ONTUSDT", name: "Ontology", fallbackMax: 125 },
  { id: "AR", weex: "ARUSDT", name: "Arweave", fallbackMax: 75 },
  { id: "QTUM", weex: "QTUMUSDT", name: "Qtum", fallbackMax: 75 },
  { id: "CELO", weex: "CELOUSDT", name: "Celo", fallbackMax: 50 },
  { id: "KSM", weex: "KSMUSDT", name: "Kusama", fallbackMax: 50 },
  { id: "ZETA", weex: "ZETAUSDT", name: "ZetaChain", fallbackMax: 75 },
  { id: "BERA", weex: "BERAUSDT", name: "Berachain", fallbackMax: 75 },
  { id: "PLUME", weex: "PLUMEUSDT", name: "Plume", fallbackMax: 75 },
  { id: "LINEA", weex: "LINEAUSDT", name: "Linea", fallbackMax: 100 },
  { id: "STXX", weex: "STXXUSDT", name: "Stacks", fallbackMax: 20 },
  { id: "TWT", weex: "TWTUSDT", name: "Trust Wallet", fallbackMax: 125 },
  { id: "SSV", weex: "SSVUSDT", name: "SSV", fallbackMax: 75 },
  { id: "LPT", weex: "LPTUSDT", name: "Livepeer", fallbackMax: 75 },
  { id: "RSR", weex: "RSRUSDT", name: "Reserve Rights", fallbackMax: 125 },
  { id: "SUSHI", weex: "SUSHIUSDT", name: "Sushi", fallbackMax: 125 },
  { id: "ZRX", weex: "ZRXUSDT", name: "0x", fallbackMax: 125 },
  { id: "LRC", weex: "LRCUSDT", name: "Loopring", fallbackMax: 125 },
  { id: "UMA", weex: "UMAUSDT", name: "UMA", fallbackMax: 75 },
  { id: "LUNC", weex: "LUNCUSDT", name: "Terra Classic", fallbackMax: 200 },
  { id: "BAND", weex: "BANDUSDT", name: "Band", fallbackMax: 125 },
  { id: "TRB", weex: "TRBUSDT", name: "Tellor", fallbackMax: 75 },
  { id: "IOST", weex: "IOSTUSDT", name: "IOST", fallbackMax: 50 },
  { id: "CTSI", weex: "CTSIUSDT", name: "Cartesi", fallbackMax: 125 },
  { id: "USUAL", weex: "USUALUSDT", name: "Usual", fallbackMax: 100 },
  { id: "ID", weex: "IDUSDT", name: "SPACE ID", fallbackMax: 125 },
  { id: "AERO", weex: "AEROUSDT", name: "Aerodrome", fallbackMax: 100 },
  { id: "EDU", weex: "EDUUSDT", name: "Open Campus", fallbackMax: 75 },
  { id: "ACE", weex: "ACEUSDT", name: "Fusionist", fallbackMax: 75 },
  { id: "KAIA", weex: "KAIAUSDT", name: "Kaia", fallbackMax: 100 },
  { id: "ALT", weex: "ALTUSDT", name: "AltLayer", fallbackMax: 100 },
  { id: "REZ", weex: "REZUSDT", name: "Renzo", fallbackMax: 100 },
  { id: "BB", weex: "BBUSDT", name: "BounceBit", fallbackMax: 100 },
  { id: "LISTA", weex: "LISTAUSDT", name: "Lista", fallbackMax: 75 },
  { id: "HYPER", weex: "HYPERUSDT", name: "Hyper", fallbackMax: 100 },
  { id: "SONIC", weex: "SONICUSDT", name: "Sonic", fallbackMax: 50 },
  { id: "TNSR", weex: "TNSRUSDT", name: "Tensor", fallbackMax: 75 },
  { id: "SAGA", weex: "SAGAUSDT", name: "Saga", fallbackMax: 100 },
  { id: "ORCA", weex: "ORCAUSDT", name: "Orca", fallbackMax: 50 },
  { id: "W", weex: "WUSDT", name: "Wormhole", fallbackMax: 125 },
  { id: "AEVO", weex: "AEVOUSDT", name: "Aevo", fallbackMax: 100 },
  { id: "BANANA", weex: "BANANAUSDT", name: "Banana Gun", fallbackMax: 75 },
  { id: "MAV", weex: "MAVUSDT", name: "Maverick", fallbackMax: 75 },
  { id: "MORPHO", weex: "MORPHOUSDT", name: "Morpho", fallbackMax: 100 },
  { id: "BIO", weex: "BIOUSDT", name: "Bio Protocol", fallbackMax: 50 },
  { id: "POLYX", weex: "POLYXUSDT", name: "Polymesh", fallbackMax: 75 },
  { id: "LAYER", weex: "LAYERUSDT", name: "Solayer", fallbackMax: 50 },
  { id: "COTI", weex: "COTIUSDT", name: "COTI", fallbackMax: 125 },
  { id: "CVC", weex: "CVCUSDT", name: "Civic", fallbackMax: 75 },
  { id: "DASH", weex: "DASHUSDT", name: "Dash", fallbackMax: 75 },
  { id: "INIT", weex: "INITUSDT", name: "Initia", fallbackMax: 50 },
  { id: "ZIL", weex: "ZILUSDT", name: "Zilliqa", fallbackMax: 125 },
  { id: "RED", weex: "REDUSDT", name: "RedStone", fallbackMax: 50 },
  { id: "ANKR", weex: "ANKRUSDT", name: "Ankr", fallbackMax: 125 },
  { id: "ONE", weex: "ONEUSDT", name: "Harmony", fallbackMax: 125 },
  { id: "HOT", weex: "HOTUSDT", name: "Holo", fallbackMax: 125 },
  { id: "VTHO", weex: "VTHOUSDT", name: "VeThor", fallbackMax: 100 },
  { id: "SXT", weex: "SXTUSDT", name: "Space and Time", fallbackMax: 50 },
  { id: "BANANA31", weex: "BANANAS31USDT", name: "Banana For Scale", fallbackMax: 100 },
  { id: "ACT", weex: "ACTUSDT", name: "Act I", fallbackMax: 20 },
  { id: "RESOLV", weex: "RESOLVUSDT", name: "Resolv", fallbackMax: 100 },
  { id: "NIL", weex: "NILUSDT", name: "Nillion", fallbackMax: 50 },
  { id: "C98", weex: "C98USDT", name: "Coin98", fallbackMax: 50 },
  { id: "SPELL", weex: "SPELLUSDT", name: "Spell", fallbackMax: 125 },
  { id: "ACH", weex: "ACHUSDT", name: "Alchemy Pay", fallbackMax: 50 },
  { id: "USTC", weex: "USTCUSDT", name: "TerraClassicUSD", fallbackMax: 75 },
  { id: "ETHW", weex: "ETHWUSDT", name: "EthereumPoW", fallbackMax: 50 },
  { id: "BSV", weex: "BSVUSDT", name: "Bitcoin SV", fallbackMax: 50 },
  { id: "MOVR", weex: "MOVRUSDT", name: "Moonriver", fallbackMax: 50 },
  { id: "ASTR", weex: "ASTRUSDT", name: "Astar", fallbackMax: 75 },
  { id: "AUCTION", weex: "AUCTIONUSDT", name: "Bounce", fallbackMax: 75 },
  { id: "POWR", weex: "POWRUSDT", name: "Powerledger", fallbackMax: 75 },
  { id: "LQTY", weex: "LQTYUSDT", name: "Liquity", fallbackMax: 50 },
  { id: "ARPA", weex: "ARPAUSDT", name: "ARPA", fallbackMax: 100 },
  { id: "MTL", weex: "MTLUSDT", name: "Metal", fallbackMax: 75 },
  { id: "BEL", weex: "BELUSDT", name: "Bella", fallbackMax: 75 },
  { id: "WAVES", weex: "WAVESUSDT", name: "Waves", fallbackMax: 75 },
  { id: "RIF", weex: "RIFUSDT", name: "Rootstock Infra", fallbackMax: 75 },
  { id: "CORE", weex: "COREUSDT", name: "Core", fallbackMax: 50 },
  { id: "BNT", weex: "BNTUSDT", name: "Bancor", fallbackMax: 75 },
  { id: "SNT", weex: "SNTUSDT", name: "Status", fallbackMax: 75 },
  { id: "RPL", weex: "RPLUSDT", name: "Rocket Pool", fallbackMax: 50 },
  { id: "ATH", weex: "ATHUSDT", name: "Aethir", fallbackMax: 100 },
  { id: "AXL", weex: "AXLUSDT", name: "Axelar", fallbackMax: 100 },
  { id: "MERL", weex: "MERLUSDT", name: "Merlin", fallbackMax: 100 },
  { id: "SAFE", weex: "SAFEUSDT", name: "Safe", fallbackMax: 75 },
  { id: "MOVE", weex: "MOVEUSDT", name: "Movement", fallbackMax: 100 },
  { id: "KAITO", weex: "KAITOUSDT", name: "Kaito", fallbackMax: 100 },
  { id: "JOE", weex: "JOEUSDT", name: "Trader Joe", fallbackMax: 50 },
  { id: "S", weex: "SUSDT", name: "Sonic", fallbackMax: 125 },
  { id: "MNT", weex: "MNTUSDT", name: "Mantle", fallbackMax: 125 },
  { id: "MELANIA", weex: "MELANIAUSDT", name: "Melania", fallbackMax: 75 },
  { id: "DOGS", weex: "DOGSUSDT", name: "Dogs", fallbackMax: 100 },
  { id: "NOT", weex: "NOTUSDT", name: "Notcoin", fallbackMax: 100 },
  { id: "HMSTR", weex: "HMSTRUSDT", name: "Hamster", fallbackMax: 100 },
  { id: "CATI", weex: "CATIUSDT", name: "Catizen", fallbackMax: 75 },
  { id: "STG", weex: "STGUSDT", name: "Stargate", fallbackMax: 50 },
  { id: "TOSHI", weex: "TOSHIUSDT", name: "Toshi", fallbackMax: 100 },
  { id: "WEN", weex: "WENUSDT", name: "Wen", fallbackMax: 75 },
  { id: "AUDIO", weex: "AUDIOUSDT", name: "Audius", fallbackMax: 50 },
  { id: "IOTX", weex: "IOTXUSDT", name: "IoTeX", fallbackMax: 50 },
  { id: "VELO", weex: "VELOUSDT", name: "Velo", fallbackMax: 50 },
  { id: "PAXG", weex: "PAXGUSDT", name: "PAX Gold", fallbackMax: 50 },
  { id: "ZORA", weex: "ZORAUSDT", name: "Zora", fallbackMax: 75 },
  { id: "H", weex: "HUSDT", name: "Humanity", fallbackMax: 75 },
  { id: "GAS", weex: "GASUSDT", name: "Gas", fallbackMax: 50 },
  { id: "XVS", weex: "XVSUSDT", name: "Venus", fallbackMax: 50 },
  { id: "LSK", weex: "LSKUSDT", name: "Lisk", fallbackMax: 50 },
  { id: "SFP", weex: "SFPUSDT", name: "SafePal", fallbackMax: 50 },
  { id: "T", weex: "TUSDT", name: "Threshold", fallbackMax: 100 },
];

export const TOP25_WEEX = TOP25.map((c) => c.weex);

/** Price-discovery / no history — never hunt, cancel working. */
export const SKIP_WEEX = new Set(["HYPEUSDT", "TONUSDT", "GRAMUSDT", "TRXUSDT"]);

/** Until $10k: only the tight books. */
export const CORE_WEEX = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "SOLUSDT"] as const;
export const CORE_SET = new Set<string>(CORE_WEEX);

export function coinByWeex(symbol: string): AutoCoin {
  return TOP25.find((c) => c.weex === symbol) ?? TOP25[0]!;
}
