/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AliveRouteImport } from './routes/alive'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WRouteImport } from './routes/w'
import { Route as BotBotIdRouteImport } from './routes/bot.$botId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliveRoute = AliveRouteImport.update({
  id: '/alive',
  path: '/alive',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const BotBotIdRoute = BotBotIdRouteImport.update({
  id: '/bot/$botId',
  path: '/bot/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alive': typeof AliveRoute
  '/auto': typeof AutoRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/w': typeof WRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alive': typeof AliveRoute
  '/auto': typeof AutoRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/w': typeof WRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alive': typeof AliveRoute
  '/auto': typeof AutoRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/w': typeof WRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alive'
    | '/auto'
    | '/live'
    | '/login'
    | '/w'
    | '/bot/$botId'
    | '/api/auth/$'
    | '/api/cron/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alive'
    | '/auto'
    | '/live'
    | '/login'
    | '/w'
    | '/bot/$botId'
    | '/api/auth/$'
    | '/api/cron/tick'
  id:
    | '__root__'
    | '/'
    | '/alive'
    | '/auto'
    | '/live'
    | '/login'
    | '/w'
    | '/bot/$botId'
    | '/api/auth/$'
    | '/api/cron/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliveRoute: typeof AliveRoute
  AutoRoute: typeof AutoRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  WRoute: typeof WRoute
  BotBotIdRoute: typeof BotBotIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alive': {
      id: '/alive'
      path: '/alive'
      fullPath: '/alive'
      preLoaderRoute: typeof AliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/$botId': {
      id: '/bot/$botId'
      path: '/bot/$botId'
      fullPath: '/bot/$botId'
      preLoaderRoute: typeof BotBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliveRoute: AliveRoute,
  AutoRoute: AutoRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  WRoute: WRoute,
  BotBotIdRoute: BotBotIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronTickRoute: ApiCronTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
